/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package printhouseclient.view.hrmanagerviews;

import controller.SalaryChangeController;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.SalaryChange;
import printhouseclient.connection.ServerConnector;

/**
 *
 * @author sranga
 */
public class ChangeSalaryDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChangeSalaryDialog
     */
    private double changedAmount = 0.0;
    private int rawNumber = SalaryFrame.salaryTable.getSelectedRow();
    private double currentAdition = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 4); //adition column index is 5     
    private double currentDeduction = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 5); //deduction column index is 6     
    //private double currentTotal = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 6); //total column index is 5     
    private SalaryChangeController salaryChangeController;
    private ServerConnector serverConnector;

    public ChangeSalaryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            serverConnector = ServerConnector.getServerConnector();
            salaryChangeController = serverConnector.getSalaryChangeControler();
            initComponents();
            initDate();
            saveButton.setEnabled(false);
        } catch (NotBoundException ex) {
            Logger.getLogger(ChangeSalaryDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ChangeSalaryDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ChangeSalaryDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aditionText = new javax.swing.JTextField();
        deductionText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        discriptionText = new javax.swing.JTextArea();
        DateLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Salary");

        jLabel1.setText("Employee Details");

        jLabel2.setText("Name");

        jLabel5.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDLabel))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel3.setText("Change Salary");

        jLabel6.setText("Adition");

        aditionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aditionTextFocusLost(evt);
            }
        });
        aditionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aditionTextActionPerformed(evt);
            }
        });
        aditionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aditionTextKeyPressed(evt);
            }
        });

        deductionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deductionTextFocusLost(evt);
            }
        });
        deductionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductionTextActionPerformed(evt);
            }
        });
        deductionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deductionTextKeyPressed(evt);
            }
        });

        jLabel7.setText("Deduction");

        jLabel8.setText("Description");

        discriptionText.setColumns(20);
        discriptionText.setRows(5);
        discriptionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discriptionTextKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(discriptionText);

        DateLabel.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aditionText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deductionText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel)))
                    .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aditionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(deductionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(dateLabel))
                .addContainerGap())
        );

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Changes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(saveButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aditionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aditionTextActionPerformed
        // TODO add your handling code here:
        try {///check validation
            this.changedAmount = Double.parseDouble(aditionText.getText());
        } catch (Exception e) {
            aditionText.setText(null);
            aditionText.requestFocus();
        }
        if (!aditionText.getText().isEmpty()) {
            discriptionText.requestFocus();
        }

    }//GEN-LAST:event_aditionTextActionPerformed

    private void deductionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductionTextActionPerformed
        try {///check validation
            this.changedAmount = Double.parseDouble(deductionText.getText());
        } catch (Exception e) {
            deductionText.setText(null);
            deductionText.requestFocus();
        }
        if (!deductionText.getText().isEmpty()) {
            discriptionText.requestFocus();
        }
    }//GEN-LAST:event_deductionTextActionPerformed

    private void aditionTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aditionTextKeyPressed
        deductionText.setText(null);
    }//GEN-LAST:event_aditionTextKeyPressed

    private void deductionTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductionTextKeyPressed
        aditionText.setText(null);
    }//GEN-LAST:event_deductionTextKeyPressed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        if (!aditionText.getText().isEmpty()) {

            try {
                Object rowDate[] = {null, dateLabel.getText(), discriptionText.getText(), aditionText.getText(), null};
                SalaryFrame.discriptiondtm.addRow(rowDate);
                SalaryFrame.discriptionTable.revalidate();
                SalaryChange salaryChange = new SalaryChange(discriptionText.getText(),"amount", changedAmount, Integer.parseInt(IDLabel.getText()));
                salaryChangeController.addSalaryChange(salaryChange);
            } catch (RemoteException ex) {
                Logger.getLogger(ChangeSalaryDialog.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ChangeSalaryDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (!deductionText.getText().isEmpty()) {

            Object rowDate[] = {null, dateLabel.getText(), discriptionText.getText(), null, aditionText.getText()};

            SalaryFrame.discriptiondtm.addRow(rowDate);
            SalaryFrame.discriptionTable.revalidate();
        }

        writeSalaryChangeTable();
        aditionText.setText(null);
        deductionText.setText(null);
        discriptionText.setText(null);
        saveButton.setEnabled(false);

        getUpdatedData();


    }//GEN-LAST:event_saveButtonActionPerformed

    private void discriptionTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discriptionTextKeyReleased
        if (!aditionText.getText().isEmpty() || !deductionText.getText().isEmpty()) {
            saveButton.setEnabled(true);
        }
    }//GEN-LAST:event_discriptionTextKeyReleased

    private void aditionTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aditionTextFocusLost
        try {///check validation
            this.changedAmount = Double.parseDouble(aditionText.getText());
        } catch (Exception e) {
            aditionText.setText(null);
        }
        if (!aditionText.getText().isEmpty()) {
            discriptionText.requestFocus();
        }

    }//GEN-LAST:event_aditionTextFocusLost

    private void deductionTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deductionTextFocusLost
        try {///check validation
            this.changedAmount = Double.parseDouble(deductionText.getText());
        } catch (Exception e) {
            deductionText.setText(null);
        }
        if (!deductionText.getText().isEmpty()) {
            discriptionText.requestFocus();
        }
    }//GEN-LAST:event_deductionTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeSalaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeSalaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeSalaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeSalaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeSalaryDialog dialog = new ChangeSalaryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    public javax.swing.JLabel IDLabel;
    private javax.swing.JTextField aditionText;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField deductionText;
    private javax.swing.JTextArea discriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel nameLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void initDate() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        dateLabel.setText(dateFormat.format(cal.getTime()));

    }

    private void getUpdatedData() {
        this.changedAmount = 0.0;
        this.rawNumber = SalaryFrame.salaryTable.getSelectedRow();
        this.currentAdition = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 4); //adition column index is 5     
        this.currentDeduction = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 5); //deduction column index is 6     
        //this.currentTotal = (double) SalaryFrame.salaryTable.getValueAt(rawNumber, 6); //total column index is 5     
    }

    private void updateSalaryChangeTable(String state) {///state is addition or dedction
//        String sql;
//        sql = "INSERT INTO salarychange (discription,state,amount, employeeId) VALUES('advaces','addition',100,1)";
//        try {
//       //     int result = DBHandle.setData(DBConnection.getDBConnection().getConnection(), sql);
//        //} catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(Salary.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }

    public void writeSalaryChangeTable() {
        String stateString;
        String amountString;
        if (!aditionText.getText().isEmpty()) {
            stateString = "addition";
            amountString = aditionText.getText();

        } else {
            amountString = deductionText.getText();
            stateString = "diduction";

        }
        String idString = IDLabel.getText();

    }

}
