/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package printhouseclient.view.hrmanagerviews;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type;
import controller.EmployeeController;
import controller.SalaryChangeController;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.SalaryChange;
import printhouseclient.connection.ServerConnector;

/**
 *
 * @author neo
 */
public class SalaryFrame extends javax.swing.JInternalFrame {

    DefaultTableModel salarydtm;
    public static DefaultTableModel discriptiondtm;

    EmployeeController employeeController;
    ServerConnector serverConnector;
    private SalaryChangeController salaryChangeController;
    ArrayList<Employee> employees;
    ArrayList<SalaryChange> salaryChanges;

    //ArrayList<Salarychange> salarychanges;
    public SalaryFrame() {
        super("Stock", false, false, false, true);
        try {
            initComponents();

            serverConnector = ServerConnector.getServerConnector();
            employeeController = serverConnector.getEmployeeController();
            salaryChangeController = serverConnector.getSalaryChangeControler();

            //writeSalaryChangeTable();
            salarydtm = (DefaultTableModel) salaryTable.getModel();
            discriptiondtm = (DefaultTableModel) discriptionTable.getModel();
            initDate();
            try {
                initSalaryTable();
            } catch (SQLException ex) {
                Logger.getLogger(SalaryFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            //setButton();
            salaryTable.setEnabled(true);
        } catch (NotBoundException ex) {
            Logger.getLogger(SalaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SalaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SalaryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salaryTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        changeSalaryButton = new javax.swing.JButton();
        CheckChangeButton = new javax.swing.JButton();
        employeeDetailPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        monthLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        discriptionTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(674, 549));

        titleLable.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        titleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLable.setText("Salary Table");

        salaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Due Date", "Basic", "Adition", "Deduction", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salaryTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaryTableFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(salaryTable);
        if (salaryTable.getColumnModel().getColumnCount() > 0) {
            salaryTable.getColumnModel().getColumn(0).setResizable(false);
            salaryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            salaryTable.getColumnModel().getColumn(1).setResizable(false);
            salaryTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            salaryTable.getColumnModel().getColumn(2).setResizable(false);
            salaryTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            salaryTable.getColumnModel().getColumn(3).setResizable(false);
            salaryTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            salaryTable.getColumnModel().getColumn(4).setResizable(false);
            salaryTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            salaryTable.getColumnModel().getColumn(5).setResizable(false);
            salaryTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            salaryTable.getColumnModel().getColumn(6).setResizable(false);
            salaryTable.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        changeSalaryButton.setText("Change Salary");
        changeSalaryButton.setMaximumSize(new java.awt.Dimension(100, 25));
        changeSalaryButton.setMinimumSize(new java.awt.Dimension(100, 25));
        changeSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSalaryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(changeSalaryButton);

        CheckChangeButton.setText("Check Changes");
        CheckChangeButton.setMaximumSize(new java.awt.Dimension(100, 100));
        CheckChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckChangeButton);

        jPanel3.setBackground(new java.awt.Color(153, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout employeeDetailPanelLayout = new javax.swing.GroupLayout(employeeDetailPanel);
        employeeDetailPanel.setLayout(employeeDetailPanelLayout);
        employeeDetailPanelLayout.setHorizontalGroup(
            employeeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeDetailPanelLayout.setVerticalGroup(
            employeeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        monthLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        monthLabel.setText("January 2015");

        DateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateLabel.setText("Date");

        jLabel1.setText("Name   ");

        nameLabel.setText("jLabel2");

        idLabel.setText("jLabel2");

        jLabel4.setText("ID");

        jButton1.setText("Vive Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        discriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date", "Description", "Adition", "Deduction"
            }
        ));
        jScrollPane3.setViewportView(discriptionTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(idLabel))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idLabel)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(nameLabel))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(titleLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthLabel)
                    .addComponent(DateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(employeeDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckChangeButtonActionPerformed
        try {
            int row = salaryTable.getSelectedRow();
            idLabel.setText(Integer.toString((int) salaryTable.getValueAt(row, 0)));
            nameLabel.setText((String) salaryTable.getValueAt(row, 1));

            discriptiondtm.getDataVector().removeAllElements();
            createDiscriptionTable(row +1);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_CheckChangeButtonActionPerformed

    private void changeSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSalaryButtonActionPerformed
        // TODO add your handling code here:
        
        ChangeSalaryDialog changeSalaryDialog;
        changeSalaryDialog = new ChangeSalaryDialog(null, closable);
        changeSalaryDialog.IDLabel.setText(Integer.toString((int) salaryTable.getValueAt(salaryTable.getSelectedRow(), 0)));
        changeSalaryDialog.nameLabel.setText((String) salaryTable.getValueAt(salaryTable.getSelectedRow(), 1));
        changeSalaryDialog.setVisible(true);
    }//GEN-LAST:event_changeSalaryButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salaryTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryTableFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_salaryTableFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckChangeButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton changeSalaryButton;
    public static javax.swing.JTable discriptionTable;
    private javax.swing.JPanel employeeDetailPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel nameLabel;
    public static javax.swing.JTable salaryTable;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables

    private void initDate() {

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MMMMMM-dd");
        Calendar cal = Calendar.getInstance();
        DateLabel.setText(dateFormat.format(cal.getTime()));
        dateFormat = new SimpleDateFormat("YYYY-MMMM");
        monthLabel.setText(dateFormat.format(cal.getTime()));
    }

    private void initSalaryTable() throws RemoteException, SQLException {

        System.out.println("ahsdsl");
        employees = employeeController.getEmployeesFullDetailsList();
        for (Employee employee : employees) {
            Object rowData[] = {employee.getEmployeeId(), employee.getName(), employee.getDueDate(), employee.getBasicSalary(), employee.getTotalAdition(), employee.getTotalDeduction()};
            salarydtm.addRow(rowData);
        }
        jScrollPane2.setViewportView(salaryTable);
    }

    public void createDiscriptionTable(int employeeId) throws RemoteException, SQLException {

        System.out.println(employeeId);
        salaryChanges = salaryChangeController.getSalaryChangeFullDetailsList(employeeId);
        for (SalaryChange salarychange : salaryChanges) {
            if ("addition".equals(salarychange.getState())) {
                Object rawData[] = {salarychange.getSalaryChangeId(), salarychange.getDate(), salarychange.getDiscription(), salarychange.getAmount(), null};
                discriptiondtm.addRow(rawData);
            } else {
                Object rawData[] = {salarychange.getSalaryChangeId(), salarychange.getDate(), salarychange.getDiscription(), null, salarychange.getAmount()};
                discriptiondtm.addRow(rawData);
            }

        }
        discriptionTable.revalidate();

    }
}
